import fs from "fs";
import path from "path";
import { streamText, convertToModelMessages, stepCountIs } from "ai";
import { openai } from "@ai-sdk/openai";
import { tools } from "@/lib/tools";

// Loaded once at cold-start. Generated by: pnpm generate-prompt
const promptPath = path.join(process.cwd(), "generated", "system-prompt.txt");
const systemPrompt = fs.readFileSync(promptPath, "utf-8");

export async function POST(req: Request) {
  const { messages } = await req.json();

  const result = streamText({
    model: openai("gpt-4.1"),
    system: systemPrompt,
    messages: await convertToModelMessages(messages),
    tools,
    stopWhen: stepCountIs(5),
  });

  return result.toUIMessageStreamResponse();
}
